//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminplaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termin
    {
        public long ID { get; set; }
        public long IDCalendar { get; set; }
        public long IDPerson { get; set; }
        public string Ort { get; set; }
        public string Beschreibung { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
